import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex justify-center items-center min-h-screen bg-gradient-to-br h-screen  from-rose-100 to-teal-100">
        <div className='p-8 bg-[#e7e7e7] rounded-xl shadow-2xl w-p6'>
        {children}
        </div>
        
        </body>
    </html>
  )
}
